In [17]:
import pandas as pd

result = pd.DataFrame({
    "Name":["aditya","Rohan"],
    "CGPA":[9.9,8.9]
})

print(result)

     Name  CGPA
0  aditya   9.9
1   Rohan   8.9

In [28]:
import pandas as pd

s = pd.Series([23,24,25,26])

print(s)
print(type(s))

print(s[0])
print(s[1])
print(s[2])
print(s[3])
print(s.index)

0    23
1    24
2    25
3    26
dtype: int64
<class 'pandas.core.series.Series'>
23
24
25
26
RangeIndex(start=0, stop=4, step=1)

In [5]:
import pandas as pd

# custom indexing

s = pd.Series([23,24,25,26], index = ["adam","eve","charlie","bob"])

print(s)
print(s["eve"])
print(s["adam"])

adam       23
eve        24
charlie    25
bob        26
dtype: int64
24
23

In [9]:
# vectorization operation
import pandas as pd

s1 = pd.Series([1,2,3,4,5,6,])
s2 = pd.Series([7,8,9,10,11,12])

print(s1 + s2)

0     8
1    10
2    12
3    14
4    16
5    18
dtype: int64

In [43]:
# mutable value but immutable size
import pandas as pd

s = pd.Series([1,2,3,4,5,6])
s[0] = 100

#print(s)

changed_s.drop(2)
changed_s = s
print(s)
print(changed_s)

0    100
1      2
2      3
3      4
4      5
5      6
dtype: int64
0    100
1      2
2      3
3      4
4      5
5      6
dtype: int64

In [21]:
# creating dataframe in pandas using dictionary
import pandas as pd

info = {
    "name":["aditya","rohan","mohan","sohan"],
    "marks":[10,9.5,8.5,7.5],
    "grade":["A","B","C","D"]
}

df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index)
print(df.columns)

     name  marks grade
0  aditya   10.0     A
1   rohan    9.5     B
2   mohan    8.5     C
3   sohan    7.5     D
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'marks', 'grade'], dtype='object')

In [25]:
# creating dataframe using numpy array
import numpy as np
import pandas as pd

np_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(np_array)
print(df)
print(type(df))
print(type(np_array))

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>

In [26]:
# working with csv files
import pandas as pd

df_csv = pd.read_csv("student.csv")
print(df_csv)

    Student_ID    Name  Gender  Age  English  Hindi  Maths  Science  Computer  \
0          101  Aditya    Male   24       85     92     78       88        95
1          102   Rohan    Male   23       72     68     85       79        88
2          103   Priya  Female   22       91     89     94       92        96
3          104    Neha  Female   21       78     84     76       81        89
4          105    Amit    Male   23       65     72     69       74        80
5          106   Sneha  Female   22       88     95     91       87        93
6          107   Rahul    Male   24       56     64     72       68        75
7          108   Pooja  Female   21       93     90     97       95        98
8          109   Vikas    Male   23       74     70     81       76        85
9          110  Anjali  Female   22       82     88     79       85        91
10         111   Karan    Male   24       69     75     73       70        78
11         112  Simran  Female   21       95     94     92       96        99
12         113  Manish    Male   23       61     67     58       65        72
13         114   Kavya  Female   22       87     91     89       90        94
14         115  Sachin    Male   24       79     73     84       82        87

    Attendance
0           92
1           87
2           96
3           90
4           82
5           94
6           78
7           97
8           86
9           91
10          80
11          98
12          76
13          93
14          89

In [7]:
# attributes
import pandas as pd

info = {
    "name":["aditya","rohan","mohan","Sohan","ishan"],
    "age":[25,56,27,28,29],
    "city":["Mumbai","delhi","banglore","chennai","bihar"]
}

df = pd.DataFrame(info)
#print(df)
#print(df.head(2))
#print(df.tail(1))
#df.sample(5)
#df.describe()
#print(df.describe())
#print(df.shape)
#print(df.columns)
print(df.loc[0:2])
#print(df.sample(5))

     name  age      city
0  aditya   25    Mumbai
1   rohan   56     delhi
2   mohan   27  banglore

In [17]:
# selecting single cell

import pandas as pd

info = {
    "name":["aditya","rohan","mohan","Sohan","ishan"],
    "age":[25,56,27,28,29],
    "city":["Mumbai","delhi","banglore","chennai","bihar"]
}

df = pd.DataFrame(info)

df.at[0,"city"]
df.at[1,"name"]
df.iat[0,0]

'aditya'

In [14]:
# boolean fileatring
import pandas as pd

datai = {
    "ID":[101,102,103,104,105,106,107,108,109,110],
    "name":["aditya","rohan","sohan","mohan","Pohan","tohan","abhishek","sudish","nitish","ritnesh"],
    "department":["Manager","Finance","HR","Accoutant","Finance","HR","Accoutant","Finance","HR","Finance"],
    "salary":[125000,120000,150000,110000,100000,105000,90000,85000,80000,75000]
}

df = pd.DataFrame(datai)
print(df)

    ID      name department  salary
0  101    aditya    Manager  125000
1  102     rohan    Finance  120000
2  103     sohan         HR  150000
3  104     mohan  Accoutant  110000
4  105     Pohan    Finance  100000
5  106     tohan         HR  105000
6  107  abhishek  Accoutant   90000
7  108    sudish    Finance   85000
8  109    nitish         HR   80000
9  110   ritnesh    Finance   75000

In [53]:
# From above table

print(df[(df["salary"]>104000) & (df["department"]=="Finance")])
print("========== Finance Dep ===========")
print(df[df["department"]=="Finance"])
print("=========== Hr Dept ==============")
print(df[df["department"]=="HR"])

    ID   name department  salary
1  102  rohan    Finance  120000
========== Finance Dep ===========
    ID     name department  salary
1  102    rohan    Finance  120000
4  105    Pohan    Finance  100000
7  108   sudish    Finance   85000
9  110  ritnesh    Finance   75000
=========== Hr Dept ==============
    ID    name department  salary
2  103   sohan         HR  150000
5  106   tohan         HR  105000
8  109  nitish         HR   80000

In [65]:
# query like a sql method

df.query("salary > 104000 and department == 'HR'")

    ID   name department  salary
2  103  sohan         HR  150000
5  106  tohan         HR  105000

In [17]:
# data cleaning
import pandas as pd

data = pd.read_csv("data_clean.csv")
data = pd.DataFrame(data)
print(data)

    employee_id first_name last_name   age                email country  \
0             1     Aditya     Yadav  21.0   aditya@example.com   India
1             2      Rohan    Sharma  22.0    rohan@example.com   India
2             3      Priya     Patel   NaN    priya@example.com   India
3             4       Amit     Kumar  24.0     amit@example.com   India
4             5      Sneha     Verma  23.0    sneha@example.com   india
5             6      Rahul     Singh  25.0    rahul@example.com   India
6             7       Neha     Gupta  22.0         neha@example   India
7             8      Vikas     Mehta  27.0    vikas@example.com   INDIA
8             9      Karan     Joshi  26.0                  NaN   India
9            10      Pooja      Shah  24.0    pooja@example.com   India
10           11       Aman      Khan  23.0     aman@example.com   India
11           12       Neha     Gupta  22.0     neha@example.com   India
12           13      Sahil     Desai  29.0   sahil@example.com   India
13           14      Meena       Rao  31.0    meena@example.com   India
14           15      Arjun  Malhotra  28.0    arjun@example.com   India
15           16       Riya      Nair  25.0     riya@example.com   India
16           17        Dev      Bose  30.0      dev@example.com   India
17           18      Kavya      Iyer   NaN    kavya@example.com   India
18           19     Suresh     Reddy  33.0   suresh@example.com   India
19           20     Anjali    Mishra  26.0   anjali@example.com   India

      salary department joining_date
0    55000.0         IT   2026-01-15
1    62000.0    Finance   2026-01-18
2    58000.0         HR   2026-01-20
3        NaN         IT   2026-01-22
4    60000.0    Finance   2026-01-25
5    72000.0      Sales   2026-02-01
6    51000.0         HR   2026-02-03
7    85000.0         IT   2026-02-05
8    68000.0      Sales   2026-02-07
9    59000.0    Finance   2026-02-09
10   55000.0    finance   2026-02-10
11   51000.0         HR   2026-02-03
12   91000.0        IT    2026-02-12
13   -5000.0    Finance   2026-02-15
14   78000.0        NaN   2026-02-17
15   65000.0      Sales   2026-02-20
16   99000.0         IT   2026-02-22
17   57000.0         HR   2026-02-25
18  105000.0    Finance   2026-02-27
19   61000.0      Sales   2026-03-01

In [21]:
# this will show the Bollean (True) data frame where is NaN

df = pd.DataFrame(data)
df.isnull()

,employee_id,first_name,last_name,age,email,country,salary,department,joining_date
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,True,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,True,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [22]:
# This will count the boolean dataframe where is NaN

df.isnull().sum()

employee_id     0
first_name      0
last_name       0
age             2
email           1
country         0
salary          1
department      1
joining_date    0
dtype: int64

In [24]:
# This drop or delete the data where value is NaN

df.dropna()

,employee_id,first_name,last_name,age,email,country,salary,department,joining_date
0,1,Aditya,Yadav,21.0,aditya@example.com,India,55000.0,IT,2026-01-15
1,2,Rohan,Sharma,22.0,rohan@example.com,India,62000.0,Finance,2026-01-18
4,5,Sneha,Verma,23.0,sneha@example.com,india,60000.0,Finance,2026-01-25
5,6,Rahul,Singh,25.0,rahul@example.com,India,72000.0,Sales,2026-02-01
6,7,Neha,Gupta,22.0,neha@example,India,51000.0,HR,2026-02-03
7,8,Vikas,Mehta,27.0,vikas@example.com,INDIA,85000.0,IT,2026-02-05
9,10,Pooja,Shah,24.0,pooja@example.com,India,59000.0,Finance,2026-02-09
10,11,Aman,Khan,23.0,aman@example.com,India,55000.0,finance,2026-02-10
11,12,Neha,Gupta,22.0,neha@example.com,India,51000.0,HR,2026-02-03
12,13,Sahil,Desai,29.0,sahil@example.com,India,91000.0,IT,2026-02-12
13,14,Meena,Rao,31.0,meena@example.com,India,-5000.0,Finance,2026-02-15
15,16,Riya,Nair,25.0,riya@example.com,India,65000.0,Sales,2026-02-20
16,17,Dev,Bose,30.0,dev@example.com,India,99000.0,IT,2026-02-22
18,19,Suresh,Reddy,33.0,suresh@example.com,India,105000.0,Finance,2026-02-27
19,20,Anjali,Mishra,26.0,anjali@example.com,India,61000.0,Sales,2026-03-01

In [30]:
# This will fill NaN with values

df.fillna(0)

,employee_id,first_name,last_name,age,email,country,salary,department,joining_date
0,1,Aditya,Yadav,21.0,aditya@example.com,India,55000.0,IT,2026-01-15
1,2,Rohan,Sharma,22.0,rohan@example.com,India,62000.0,Finance,2026-01-18
2,3,Priya,Patel,0.0,priya@example.com,India,58000.0,HR,2026-01-20
3,4,Amit,Kumar,24.0,amit@example.com,India,0.0,IT,2026-01-22
4,5,Sneha,Verma,23.0,sneha@example.com,india,60000.0,Finance,2026-01-25
5,6,Rahul,Singh,25.0,rahul@example.com,India,72000.0,Sales,2026-02-01
6,7,Neha,Gupta,22.0,neha@example,India,51000.0,HR,2026-02-03
7,8,Vikas,Mehta,27.0,vikas@example.com,INDIA,85000.0,IT,2026-02-05
8,9,Karan,Joshi,26.0,0,India,68000.0,Sales,2026-02-07
9,10,Pooja,Shah,24.0,pooja@example.com,India,59000.0,Finance,2026-02-09
10,11,Aman,Khan,23.0,aman@example.com,India,55000.0,finance,2026-02-10
11,12,Neha,Gupta,22.0,neha@example.com,India,51000.0,HR,2026-02-03
12,13,Sahil,Desai,29.0,sahil@example.com,India,91000.0,IT,2026-02-12
13,14,Meena,Rao,31.0,meena@example.com,India,-5000.0,Finance,2026-02-15
14,15,Arjun,Malhotra,28.0,arjun@example.com,India,78000.0,0,2026-02-17
15,16,Riya,Nair,25.0,riya@example.com,India,65000.0,Sales,2026-02-20
16,17,Dev,Bose,30.0,dev@example.com,India,99000.0,IT,2026-02-22
17,18,Kavya,Iyer,0.0,kavya@example.com,India,57000.0,HR,2026-02-25
18,19,Suresh,Reddy,33.0,suresh@example.com,India,105000.0,Finance,2026-02-27
19,20,Anjali,Mishra,26.0,anjali@example.com,India,61000.0,Sales,2026-03-01

In [84]:
# Convertinf string into int
import pandas as pd

datas = {
    "ID":[101,102,103,104,105,106,107,108,109,110],
    "name":["aditya "," rohan","soh an","mo han","Pohan","Tohan","Abhishek","sudish","nitish","ritnesh"],
    "department":["Manager","Finance","HR","Accoutant","Finance","HR","Accoutant","Finance","HR","Finance"],
    "salary":[125000,120000,150000,110000,100000,105000,90000,85000,80000,75000]
}

df = pd.DataFrame(datas)
print(df)

    ID      name department  salary
0  101   aditya     Manager  125000
1  102     rohan    Finance  120000
2  103    soh an         HR  150000
3  104    mo han  Accoutant  110000
4  105     Pohan    Finance  100000
5  106     Tohan         HR  105000
6  107  Abhishek  Accoutant   90000
7  108    sudish    Finance   85000
8  109    nitish         HR   80000
9  110   ritnesh    Finance   75000

In [85]:
# changing data types

df[df["salary"] == df["salary"].astype(int)]
print(type(df["salary"]))

<class 'pandas.core.series.Series'>

In [86]:
# Convert to lowercase

df["name"]=df["name"].str.lower()
df["name"]=df["name"].str.capitalize()
df["name"]=df["name"].str.strip()
df["name"]=df["name"].str.split(" ")
#df["name"]=df["name"].str.contains("name")
print(df)

    ID        name department  salary
0  101    [Aditya]    Manager  125000
1  102     [rohan]    Finance  120000
2  103   [Soh, an]         HR  150000
3  104   [Mo, han]  Accoutant  110000
4  105     [Pohan]    Finance  100000
5  106     [Tohan]         HR  105000
6  107  [Abhishek]  Accoutant   90000
7  108    [Sudish]    Finance   85000
8  109    [Nitish]         HR   80000
9  110   [Ritnesh]    Finance   75000